Puzzle 1 
Todo:
- Parse Coords
- Figure how to plot for one guy
- Plot every claim
- Filter array for more than one claim
-) Count spaces

In [13]:
def getCoords(line):
    coords = {"start_x":0, "start_y":0, "end_x":0, "end_y":0}
    at_pos = line.find("@")
    com_pos = line.find(",")
    col_pos = line.find(":")
    x_pos = line.find("x")
    
    coords["start_x"] = int(line[at_pos + 2 : com_pos])
    coords["start_y"] = int(line[com_pos + 1 : col_pos])
    coords["end_x"] = coords["start_x"] + int(line[col_pos + 2 : x_pos]) - 1
    coords["end_y"] = coords["start_y"] + int(line[x_pos + 1:]) - 1
    return coords

def test_getCoords():
    test_line = "#1 @ 1,3: 4x4"
    coords = getCoords(test_line)
    try:
        assert coords["start_x"] == 1, "start x is wrong"
        assert coords["start_y"] == 3, "start y is wrong"
        assert coords["end_x"] == 4, "end x is wrong"
        assert coords["end_y"] == 6, "end y is wrong"
        print("test_passed")
    except AssertionError as e:
        print ("Test Failed: ", e)
        
   
test_getCoords()

test_passed


In [37]:
import numpy as np
# test plotting
# remember indexing is [y, x]
test_cloth = np.zeros((9,11))
test_cloth[2 : 2 + 4, 3 : 3 + 5] = 1
test_cloth[2 : 2 + 2, 3 : 3 + 2] += 1
test_cloth[3 : 6, 5:8] += 1
print(test_cloth)

check = test_cloth[test_cloth > 1]
print(check)
print(len(check))

print(test_cloth[2:4,3:5].sum())

unq = np.unique(test_cloth)
print(unq)
for el in unq:
    if el != 0:
        print (el)
print(sum(unq))

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  2.  2.  1.  1.  1.  0.  0.  0.]
 [ 0.  0.  0.  2.  2.  2.  2.  2.  0.  0.  0.]
 [ 0.  0.  0.  1.  1.  2.  2.  2.  0.  0.  0.]
 [ 0.  0.  0.  1.  1.  2.  2.  2.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]
[ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]
13
8.0
[ 0.  1.  2.]
1.0
2.0
3.0


In [28]:
# Puzzle 1 solution
cloth = np.zeros((1001,1001))
with open("day3_input.txt", "r") as file:
    for line in file:
        coords = getCoords(line)
        cloth[coords["start_y"] : coords["end_y"] + 1, coords["start_x"] : coords["end_x"] + 1] += 1
overlaps = len(cloth[cloth > 1])
print(overlaps)

109785


In [30]:
def getCoords_full(line):
    coords = {"id":0,"start_x":0, "start_y":0, "end_x":0, "end_y":0}
    at_pos = line.find("@")
    com_pos = line.find(",")
    col_pos = line.find(":")
    x_pos = line.find("x")
    
    coords["id"] = int(line[1: at_pos - 1])
    coords["start_x"] = int(line[at_pos + 2 : com_pos])
    coords["start_y"] = int(line[com_pos + 1 : col_pos])
    coords["end_x"] = coords["start_x"] + int(line[col_pos + 2 : x_pos]) - 1
    coords["end_y"] = coords["start_y"] + int(line[x_pos + 1:]) - 1
    return coords

def test_getCoords_full():
    test_line = "#1 @ 1,3: 4x4"
    coords = getCoords_full(test_line)
    try:
        assert coords["id"] == 1, "id is wrong"
        assert coords["start_x"] == 1, "start x is wrong"
        assert coords["start_y"] == 3, "start y is wrong"
        assert coords["end_x"] == 4, "end x is wrong"
        assert coords["end_y"] == 6, "end y is wrong"
        print("test_passed")
    except AssertionError as e:
        print ("Test Failed: ", e)
        
   
test_getCoords_full()

test_passed


In [42]:
# Puzzle 2 solution
cloth = np.zeros((1001,1001))
with open("day3_input.txt", "r") as file:
    for line in file:
        coords = getCoords_full(line)
        
        #Get values in areas about to be claimed
        unq_vals = np.unique(cloth[coords["start_y"] : coords["end_y"] + 1, coords["start_x"] : coords["end_x"] + 1])
        #If area is unclaimed, claim it
        if len(unq_vals) == 1 and unq_vals[0] == 0:
            cloth[coords["start_y"] : coords["end_y"] + 1, coords["start_x"] : coords["end_x"] + 1] = coords["id"]
            #print("here")
        else:
            #If area is claimed nuke it
            cloth[coords["start_y"] : coords["end_y"] + 1, coords["start_x"] : coords["end_x"] + 1] = -1
            #Also nuke overlapping claims found
            for val in unq_vals:
                if val != 0:
                    cloth[cloth == val] = -1
# Get remaining values
rem_values = np.unique(cloth)
print(rem_values[(rem_values != 0) & (rem_values != -1)])

[ 504.]
